export const COUNTRIES = [
  { countryCode: "ww", currencyCode: "usd" },
  { countryCode: "ca", currencyCode: "cad" },
  // { countryCode: "us", currencyCode: "usd" },
  { countryCode: "in", currencyCode: "inr" },
  // { countryCode: "za", currencyCode: "zar" },
  // { countryCode: "au", currencyCode: "aud" },
  // { countryCode: "hk", currencyCode: "hkd" },
  // { countryCode: "jp", currencyCode: "EUR" },
  // { countryCode: "my", currencyCode: "EUR" },
  // { countryCode: "nz", currencyCode: "EUR" },
  // { countryCode: "ph", currencyCode: "EUR" },
  // { countryCode: "sg", currencyCode: "EUR" },
  // { countryCode: "tw", currencyCode: "EUR" },
  // { countryCode: "th", currencyCode: "EUR" },
  // { countryCode: "at", currencyCode: "EUR" },
  // { countryCode: "be", currencyCode: "EUR" },
  // { countryCode: "cy", currencyCode: "EUR" },
  // { countryCode: "cz", currencyCode: "EUR" },
  // { countryCode: "dk", currencyCode: "EUR" },
  // { countryCode: "ee", currencyCode: "EUR" },
  // { countryCode: "fi", currencyCode: "EUR" },
  // { countryCode: "fr", currencyCode: "EUR" },
  // { countryCode: "de", currencyCode: "EUR" },
  // { countryCode: "gr", currencyCode: "EUR" },
  // { countryCode: "ie", currencyCode: "EUR" },
  // { countryCode: "it", currencyCode: "EUR" },
  // { countryCode: "lt", currencyCode: "EUR" },
  // { countryCode: "lu", currencyCode: "EUR" },
  // { countryCode: "mt", currencyCode: "EUR" },
  // { countryCode: "nl", currencyCode: "EUR" },
  // { countryCode: "no", currencyCode: "EUR" },
  // { countryCode: "pl", currencyCode: "EUR" },
  // { countryCode: "pt", currencyCode: "EUR" },
  // { countryCode: "ro", currencyCode: "EUR" },
  // { countryCode: "sk", currencyCode: "EUR" },
  // { countryCode: "si", currencyCode: "EUR" },
  // { countryCode: "es", currencyCode: "EUR" },
  // { countryCode: "se", currencyCode: "EUR" },
  // { countryCode: "ch", currencyCode: "EUR" },
  // { countryCode: "tr", currencyCode: "EUR" },
  // { countryCode: "gb", currencyCode: "EUR" },
  // { countryCode: "ar", currencyCode: "EUR" },
  // { countryCode: "br", currencyCode: "EUR" },
  // { countryCode: "cl", currencyCode: "EUR" },
  // { countryCode: "co", currencyCode: "EUR" },
  // { countryCode: "mx", currencyCode: "EUR" },
  // { countryCode: "pe", currencyCode: "EUR" },
];
