export const COUNTRIES = [
  { countryCode: "ww", countryName: "Worldwide", currencyCode: "usd" },
  { countryCode: "ca", countryName: "Canada", currencyCode: "cad" },
  { countryCode: "us", countryName: "United States", currencyCode: "usd" },
  { countryCode: "in", countryName: "India", currencyCode: "inr" },
  { countryCode: "za", countryName: "South Africa", currencyCode: "zar" },
  { countryCode: "au", countryName: "Australia", currencyCode: "aud" },
  { countryCode: "hk", countryName: "Hong Kong", currencyCode: "hkd" },
  { countryCode: "jp", countryName: "Japan", currencyCode: "jpy" },
  { countryCode: "my", countryName: "Malaysia", currencyCode: "myr" },
  { countryCode: "nz", countryName: "New Zealand", currencyCode: "nzd" },
  { countryCode: "ph", countryName: "Philippines", currencyCode: "php" },
  { countryCode: "sg", countryName: "Singapore", currencyCode: "sgd" },
  { countryCode: "tw", countryName: "Taiwan", currencyCode: "twd" },
  { countryCode: "th", countryName: "Thailand", currencyCode: "usd" },
  { countryCode: "at", countryName: "Austria", currencyCode: "eur" },
  { countryCode: "be", countryName: "Belgium", currencyCode: "eur" },
  { countryCode: "cy", countryName: "Cyprus", currencyCode: "eur" },
  { countryCode: "cz", countryName: "Czech Republic", currencyCode: "czk" },
  { countryCode: "dk", countryName: "Denmark", currencyCode: "dkk" },
  { countryCode: "ee", countryName: "Estonia", currencyCode: "eur" },
  { countryCode: "fi", countryName: "Finland", currencyCode: "eur" },
  { countryCode: "fr", countryName: "France", currencyCode: "eur" },
  { countryCode: "de", countryName: "Germany", currencyCode: "eur" },
  { countryCode: "gr", countryName: "Greece", currencyCode: "eur" },
  { countryCode: "ie", countryName: "Ireland", currencyCode: "eur" },
  { countryCode: "it", countryName: "Italy", currencyCode: "eur" },
  { countryCode: "lt", countryName: "Lithuania", currencyCode: "eur" },
  { countryCode: "lu", countryName: "Luxembourg", currencyCode: "eur" },
  { countryCode: "mt", countryName: "Malta", currencyCode: "eur" },
  { countryCode: "nl", countryName: "Netherlands", currencyCode: "eur" },
  { countryCode: "no", countryName: "Norway", currencyCode: "nok" },
  { countryCode: "pl", countryName: "Poland", currencyCode: "pln" },
  { countryCode: "pt", countryName: "Portugal", currencyCode: "eur" },
  { countryCode: "ro", countryName: "Romania", currencyCode: "ron" },
  { countryCode: "sk", countryName: "Slovakia", currencyCode: "eur" },
  { countryCode: "si", countryName: "Slovenia", currencyCode: "eur" },
  { countryCode: "es", countryName: "Spain", currencyCode: "eur" },
  { countryCode: "se", countryName: "Sweden", currencyCode: "sek" },
  { countryCode: "ch", countryName: "Switzerland", currencyCode: "chf" },
  { countryCode: "tr", countryName: "Turkey", currencyCode: "try" },
  { countryCode: "gb", countryName: "United Kingdom", currencyCode: "gbp" },
  { countryCode: "ar", countryName: "Argentina", currencyCode: "usd" },
  { countryCode: "br", countryName: "Brazil", currencyCode: "brl" },
  { countryCode: "cl", countryName: "Chile", currencyCode: "clp" },
  { countryCode: "co", countryName: "Colombia", currencyCode: "cop" },
  { countryCode: "mx", countryName: "Mexico", currencyCode: "mxn" },
  { countryCode: "pe", countryName: "Peru", currencyCode: "pen" },
];
